### ISSUE TITLE
missing margin/maxwidth option

### ISSUE THREAD

**Issue by acornejo** [mk-fg/pretty-yaml#16]
From the documentation:

> Attempt is made to pick more readable string representation styles, depending on the value

It would be nice if the user could provide as an option what the default maxwidth of a line should be. Peeking at the code this seems to be fixed to a constant, aka 120 chars, however in plenty of cases it is desirable to have a different maximum width (my terminal might be smaller or larger).

**Comment by mk-fg** [comment]
Yeah, it's a weird constant indeed, thanks for pointing it out.

There's no real formatting going on though, just a decision on which string repr style to use (YAML allows for several).
You probably mean this line: https://github.com/mk-fg/pretty-yaml/blob/5488a55/pyaml/__init__.py#L121

PyYAML has controls for indent/width, which should do what you want, but these keywords weren't passed from `pyaml.dump()` before, which should be fixed in e694fe7 (on PyPI as well).

Now you should be able to do something like: `pyaml.dump(wide_and_deep, width=40)`
width=80 is the default in PyYAML, but might be worth passing it explicitly anyway).

I've added a note on the thing to the readme tricks section (last one): https://github.com/mk-fg/pretty-yaml/#some-tricks

**Comment by mk-fg** [comment]
Oh, also that decision on line-121 now uses emitter.best_width (which is set from passed/default "width"), so should also be fixed and tunable. Forgot to mention.
