### ISSUE TITLE
Multiline String as block and quoted Strings

### ISSUE THREAD

**Issue by pansen** [mk-fg/pretty-yaml#26]
Hi! 

I have some [OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) schema definition, that I'm extracting via [ApiSpec](https://apispec.readthedocs.io/en/stable/). 

```yaml
    ---
    x-extension: value
    post:
      # headline/name of the resource
      operationId: users create
      summary: Register user
      description: |
        Imagine all the users living for today

        Imagine there's no countries
        It isn't hard to do
        Nothing to kill or die for
        And no religion too

        Imagine all the users living life in peace, you
        You may say I'm a dreamer
        But I'm not the only one
        I hope some day you'll join us
        And the world will be as one

      security:
        - APIKeyHeader: []

      # this will appear as grouping in the left-side menu
      tags:
      - Legacy API

      consumes:
      - application/json
      produces:
      - application/json

      parameters:
      - in: body
        name: body
        description: Foo bar
        required: true
        schema:
          $ref: '#/components/schemas/FooBodySchema'
```

Apispec is doing all the heavy lifting, but I changed the yaml library to pretty-yaml to get rid of the Python type hints. 

## Question

Given the yaml above, how can I accomplish to receive multiline blocks as a block 

```yaml
      description: |
        Imagine all the users living for today

        Imagine there's no countries
        It isn't hard to do
        Nothing to kill or die for
        And no religion too
```

**and**

have single line Strings quoted

```yaml
        schema:
          $ref: '#/components/schemas/FooBodySchema'
```

Currently I'm using 

```python
pyaml.dump(my_spec, safe=True, force_embed=False, vspacing=[2, 1], string_val_style='"')
```

which unfortunately puts the mutline Strings in simple quotes as well. 

Thank you :)

**Comment by mk-fg** [comment]
Hi,

Current behavior in this module is to use explicitly-specified string style unconditionally, i.e. for all strings, so not possible to do what you want via simple parameter.
https://github.com/mk-fg/pretty-yaml/blob/370130d/pyaml/__init__.py#L113-L136

What I'd probably do is to subclass UnsafePrettyYAMLDumper and override represent_stringish method there to check for newlines and using `style = '|'` for these and calling original method or using `style = "'"` for everything else.
Don't remember if using `UnsafePrettyYAMLDumper.add_representer(str_type, myfunc)` will do the same, maybe can be used instead of subclassing, though latter is probably same LoC-wise and won't alter global stuff.

**Comment by mk-fg** [comment]
Actually, if you want to change existing yaml doc without breaking formatting, comments in there or anything like that, maybe also check out [ruamel.yaml](https://bitbucket.org/ruamel/yaml) module, which I've used for that recently and found to be very powerful for any kind of humane yaml stuff (esp. preserving comments is like a killer feature!).

**Comment by pansen** [comment]
Awesome, thanks a lot @mk-fg. I will check your suggestions and respond my final solution. :)
