### ISSUE TITLE
Since dict is ordered by default since 3.6, the order is lost now

### ISSUE THREAD

**Issue by pombredanne** [mk-fg/pretty-yaml#27]
The dict are sorted on dump... but there should be three cases: python2 and python3 until 3.5 should sort. 3.6 and up are ordered dicts by default, so they should NOT be sorted by default anymore IMHO.

**Comment by mk-fg** [comment]
Hi,

Thanks for bringing it up, and sorry for delay, opened it from notification and then completely forgot about this tab.

I think wrt readability, there's also an opposite argument to be made - if you have an arbitrary-ordered dict and dump it that way, it'd be hard to read and find anything there due to that lack of ordering.
Also tend to use module for diffing app data serialized to yaml/json without regard to ordering, and sorting dicts is essential for that use-case.

So I'd rather keep current behavior by default, especially since it's consistent between pythons and previous module versions, plus doesn't really violate anything.

Added `sort_dicts=False` option to bypass the sorting, which can be used either on PrettyYAMLDumper init or any of the module shortcut funcs for it (e.g. pyaml.dump).
Note that as python 3.x didn't drop collections.OrderedDict yet, so it can also be used as a wrapper if for example you want all but a few dicts auto-sorted.

Technically it is PyYAML doing the sorting in Representer.represent_dict, and this option makes overidden method call represent_odict() instead.
