### ISSUE TITLE
yaml.composer.ComposerError: expected a single document in the stream

### ISSUE THREAD

**Issue by u2mejc** [mk-fg/pretty-yaml#29]
Are concatenated yaml docs supported? I know that `pyyaml` supports them being delimited by three dashes, but I couldn't figure out if this is supported by looking at pretty-yaml's docs.

**Comment by mk-fg** [comment]
No, there wasn't a `yaml.dump_all()` method equivalent.
But since yaml.dump_all was used internally anyway, added `pyaml.dump_all([doc1, doc2, doc3])`, as well as multiple_docs=False keyword to all dump methods which is equivalent to that.
Note that it passes explicit_start=True by default, which can be disabled by passing False there instead.
