### ISSUE TITLE
RepresenterError: 'cannot represent an object' for custom object

### ISSUE THREAD

**Issue by 3rock618** [mk-fg/pretty-yaml#33]
Real simple example:

``` python
import pyaml
class Car:
    def __init__(self):
        self.make  = 'Honda'
car = Car()
pyaml.dump(car)
```
Output: 
`RepresenterError: ('cannot represent an object', <__main__.Car object at 0x7fe5f1af0c10>)`

tested `pyaml.dump(car.__dict__)` works fine
tested `import yaml; yaml.dump(car)` works fine. output: 
`'!!python/object:__main__.Car\nmake: Honda\n` (this is the output I would expect...)

What am I missing?

**Comment by mk-fg** [comment]
pyaml is only doing safe_dump iirc, serializing common data types, but not arbitrary objects.
You can probably use bunch of pyyaml parameters to get nicer output for these though, without really needing this old pyaml module.

I'd also suggest to be extra careful where you use `yaml.dump()` and `yaml.load()`, as pretty sure these are essentially `eval()` in python, so anyone who can manipulate yaml will get to run arbitrary code in any script that `yaml.load()`'s it.

**Comment by 3rock618** [comment]
Gotcha. The only feature I really need is `force_embed`. Any ideas how to this on pyyaml?

> "force_embed" option to avoid having &id stuff scattered all over the output (which might be beneficial in some cases, hence the option).

**Comment by mk-fg** [comment]
I think one way to do it would be to subclass yaml.dumper.Dumper (instead of yaml.dumper.SafeDumper like this module does) and do something like this:
https://github.com/mk-fg/pretty-yaml/blob/master/pyaml/__init__.py#L46-L48

I.e. PyYAML keeps a mapping of already-serialized nodes and looks up if some sub-node gets repeated to replace it with &id, so you can just have that mapping flushed somewhere and done - such lookup will never succeed.
Pretty sure you can use subclass with this exact function override (no need for option check either), something like 5 extra lines, perfect for your purposes.

**Comment by mk-fg** [comment]
Also, as you almost certainly using python3, it'd probably look more like this:
```
class PrettyDumper(yaml.dumper.Dumper):
  def serialize_node(self, node, parent, index):
    self.serialized_nodes.clear()
    return super().serialize_node(node, parent, index)
```
(super() can be used without extra cruft)

**Comment by 3rock618** [comment]
super().good! Seems to be working flawlessly. Thank you!
