### ISSUE TITLE
To ensure Python compatibility, it is recommended to avoid using the := operator in your code.

### ISSUE THREAD

**Issue by CFTangT** [mk-fg/pretty-yaml#42]
To ensure compatibility with lower versions of Python, please avoid using the ":=" operator in your project, as it is only available in Python 3.8 and higher versions. Please, consider alternative methods to achieve the desired functionality.

**Comment by mk-fg** [comment]
Sorry, I don't want to bother with <=3.7, python2, or other really old python releases by now.

I know that enterprise distros often stick with such for 5+ years, due to their API-stability requirements, but maybe they can backport stuff for their paid customers if they want to, or something.
Though in case of this module, I'd recomment simply sticking to older <23.x releases for now - older 3.x and even 2.7 pythons should be supported there, and there isn't that much difference otherwise.

Fixed missing 3.8+ version requirement in project metadata and README though.
Should prevent from installing a broken version on these older releases at least.

Thanks for reporting.
